name: Provider integration request
description: Request support for a fitness data provider beyond Strava.
title: "[Provider] "
labels:
  - provider
body:
  - type: input
    id: provider
    attributes:
      label: Provider name
      placeholder: Apple Health / Health Connect / Garmin / etc.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why this provider matters
      description: Describe who benefits and what data should be imported.
    validations:
      required: true
  - type: textarea
    id: api
    attributes:
      label: API or export details
      description: Links to docs, auth model, and example payloads.
